[package]
name = "aliasmgr"
version = "0.1.0"
description = "An alias manager written in Rust"
authors = ["Felipe Faria <fariafelipe22@outlook.com>"]
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
toml = "0.9.8"
